### PR TITLE
Typing and class import

### PR DESCRIPTION
**Pull request by serriaguirregaray**
Small changes to import "PipesKubeRayJobClient" and manage unsupported python version.

### CODE REVIEW

**Comment by danielgafni** [comment]
Hey, thanks for the PR! 

1. re: the import - please run `ruff check --fix` (or setup the `pre-commit` hook as the README.md [suggests](https://github.com/danielgafni/dagster-ray?tab=readme-ov-file#development)). 

2. re: `dict` -> `Dict` - as you mentioned, I'm aiming to support Python 3.9+, where this syntax is valid. However, because right now Python 3.9 syntax is not *enforced* in `dagster-ray`, I think it's ok to accept this change (it doesn't cost anything to do it). But please be aware that in the future Python 3.9 syntax **will be enforced** and all `Dict` occurrences are going to be replaced with `dict`, so be careful with updates! Python 3.8 [reached it's end of life](https://devguide.python.org/versions/) so I don't think supporting it in the long term makes sense.

**Review by danielgafni — CHANGES_REQUESTED** [review]
please run `ruff check --fix`

**Comment by serriaguirregaray** [comment]
Good to know on the python support, thank you!

**Comment by danielgafni** [comment]
No idea why doesn't CI show up; I'll just merge without it

**Pull request merged**
